#!/bin/sh

start() {
	printf "Starting hostapd: "
	start-stop-daemon -b -S -q -m -p /var/run/hostapd.pid --exec /usr/sbin/hostapd -- /etc/hostapd.conf -s
	echo "OK"
}

stop() {
	printf "Stopping hostapd: "
	start-stop-daemon -K -q -p /var/run/hostapd.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	sleep 1
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
