#!/bin/sh

case "$1" in
  start)
        echo 1 >> /proc/sys/net/ipv4/ip_forward
	nft -f /etc/nftables/nat
	;;
  stop)
	;;
  restart|reload)
	stop
	sleep 1
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
